### ISSUE TITLE
Plugin Doesn't Load on Windows

### ISSUE THREAD

**Issue by antoinne85** [edhuardotierrez/hyper-quickssh#1]
I'm far from an expert on the subject, but it seems that this part of the packages.config is preventing the plugin from loading on Windows machines.

```
"os": [
    "!win32"
  ]
```

Is there some dependency of the project that makes it incompatible with Windows or do you have some guidance on any steps you might want a contributor to take with respect to getting the plugin to be functional on Windows?

**Comment by antoinne85** [comment]
Let's just ignore this. I'm pretty sure my install of Hyper is Fubar'd. Not long after submitting this I restarted Hyper and the whole world went to hell.

**Comment by edhuardotierrez** [comment]
Thank you for your comment. I will to run some tests on windows to make sure the plugin works (I tested it on Mac only).

**Comment by Plinpod** [comment]
Has there been any progress on this? Also interested in this for Windows.
